inherit_from: .rubocop_todo.yml
require: rubocop-rails

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'bin/bundle'
    - 'db/seeds.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names